// ui/src/components/reviews.tsx
import { Star } from "lucide-react";
import { api } from "@/lib/api";
import { Avatar, AvatarFallback } from "./ui/avatar";
import { Skeleton } from "./ui/skeleton";

interface ReviewsProps {
  toiletId: string;
}

export function Reviews({ toiletId }: ReviewsProps) {
  const {
    data: reviews,
    isPending,
    isError,
  } = api.useQuery("get", "/reviews", {
    params: { query: { toilet_id: toiletId } },
  });

  if (isPending) {
    return (
      <div className="flex items-start gap-4">
        <Skeleton className="h-12 w-12 rounded-full" />
        <div className="flex w-full flex-col gap-2">
          <Skeleton className="h-12" />
          <Skeleton className="h-2" />
        </div>
      </div>
    );
  }

  if (isError) {
    return <p>An error occurred.</p>;
  }

  return (
    <div className="flex flex-col gap-4">
      <h3 className="font-semibold text-xl">Reviews ({reviews?.length ?? 0})</h3>
      {!reviews || reviews.length === 0 ? (
        <p>No reviews yet.</p>
      ) : (
        reviews.map((review) => (
          <div key={review.id} className="flex items-start gap-4">
            <Avatar>
              <AvatarFallback>AN</AvatarFallback>
            </Avatar>
            <div className="flex w-full flex-col gap-2">
              <div className="grid grid-cols-3">
                <div className="flex flex-col items-center gap-1">
                  <small>Water Pressure:</small>
                  <div className="flex">
                    {review.rating_water_pressure === 0 ? (
                      <span>💩</span>
                    ) : (
                      Array.from({ length: review.rating_water_pressure }).map(
                        (_, i) => (
                          // biome-ignore lint/suspicious/noArrayIndexKey: index is fine for static star arrays
                          <Star
                            key={i}
                            className="fill-amber-500 text-amber-500"
                            size="1rem"
                          />
                        ),
                      )
                    )}
                  </div>
                </div>
                <div className="flex flex-col items-center gap-1">
                  <small>Cleanliness:</small>
                  <div className="flex">
                    {review.rating_cleanliness === 0 ? (
                      <span>💩</span>
                    ) : (
                      Array.from({ length: review.rating_cleanliness }).map((_, i) => (
                        // biome-ignore lint/suspicious/noArrayIndexKey: index is fine for static star arrays
                        <Star
                          key={i}
                          className="fill-amber-500 text-amber-500"
                          size="1rem"
                        />
                      ))
                    )}
                  </div>
                </div>
                <div className="flex flex-col items-center gap-1">
                  <small>Poopability:</small>
                  <div className="flex">
                    {review.rating_poopability === 0 ? (
                      <span>💩</span>
                    ) : (
                      Array.from({ length: review.rating_poopability }).map((_, i) => (
                        // biome-ignore lint/suspicious/noArrayIndexKey: index is fine for static star arrays
                        <Star
                          key={i}
                          className="fill-amber-500 text-amber-500"
                          size="1rem"
                        />
                      ))
                    )}
                  </div>
                </div>
              </div>
              {review.content ? (
                <p>{review.content}</p>
              ) : (
                <p className="text-gray-400">
                  <i>No comment.</i>
                </p>
              )}
              <small className="text-gray-400">Reviewed {review.created}</small>
            </div>
          </div>
        ))
      )}
    </div>
  );
}

// ui/src/lib/components/Reviews.svelte
<script lang="ts">
  import { page } from "$app/state";
  import { api } from "$lib/api";
  import { Avatar, AvatarFallback } from "$lib/components/ui/avatar";
  import { Skeleton } from "$lib/components/ui/skeleton/index.js";
  import { createQuery } from "@tanstack/svelte-query";
  import { Star } from "lucide-svelte";

  const {
    params: { toiletId },
  } = page;

  const query = createQuery({
    queryKey: ["toilets", toiletId, "reviews"],
    queryFn: () => api.toilets.reviews(toiletId),
  });
</script>

<h3 class="text-xl font-semibold">Reviews ({$query.data?.data.length ?? 0})</h3>

{#await $query.data}
  <div class="flex items-start gap-4">
    <Skeleton class="h-12 w-12 rounded-full" />
    <div class="flex w-full flex-col gap-2">
      <Skeleton class="h-12" />
      <Skeleton class="h-2" />
    </div>
  </div>
{:then res}
  {@const data = res?.data ?? []}
  {#if data.length === 0}
    No reviews yet.
  {:else}
    {#each data as review}
      <div class="flex items-start gap-4">
        <Avatar>
          <AvatarFallback>AN</AvatarFallback>
        </Avatar>
        <div class="flex w-full flex-col gap-2">
          <div class="grid grid-cols-3">
            <div class="flex flex-col items-center gap-1">
              <small>Water Pressure:</small>
              <div class="flex">
                {#if review.rating_water_pressure === 0}
                  💩
                {:else}
                  {#each Array(review.rating_water_pressure) as _}
                    <Star class="fill-amber-500" size="1rem" />
                  {/each}
                {/if}
              </div>
            </div>
            <div class="flex flex-col items-center gap-1">
              <small>Cleanliness:</small>
              <div class="flex">
                {#if review.rating_water_pressure === 0}
                  💩
                {:else}
                  {#each Array(review.rating_cleanliness) as _}
                    <Star class="fill-amber-500" size="1rem" />
                  {/each}
                {/if}
              </div>
            </div>
            <div class="flex flex-col items-center gap-1">
              <small> Poopability: </small>
              <div class="flex">
                {#if review.rating_water_pressure === 0}
                  💩
                {:else}
                  {#each Array(review.rating_poopability) as _}
                    <Star class="fill-amber-500" size="1rem" />
                  {/each}
                {/if}
              </div>
            </div>
          </div>
          {#if review.content}
            <p>{review.content}</p>
          {:else}
            <p class="text-gray-400"><i>No comment.</i></p>
          {/if}
          <small class="text-gray-400">Reviewed {review.created}</small>
        </div>
      </div>
    {/each}
  {/if}
{:catch _}
  <p>An error occurred.</p>
{/await}
